#from alpine:latest as base
from python:3.7.3-alpine as base

from base as builder

RUN apk add --no-cache python3 python3-dev py-pip build-base

# create directory to copy files to
RUN mkdir /install/
WORKDIR /install

# copy the files that should have come from git
copy requirements.txt requirements.txt

# go ahead and install the python modules that also came from git
RUN pip install --install-option="--prefix=/install" -r requirements.txt
