FROM python:3.7.3-alpine

#copy base image configuration to main 
copy --from=289349975759.dkr.ecr.us-east-2.amazonaws.com/sample-python_base:latest /usr/local /usr/local

RUN mkdir /app/

COPY . ./

EXPOSE 8080

ENTRYPOINT ["python3", "app.py"]
