#from alpine:latest as base image for the build
#test1
from python:3.7.3-alpine as base

from base as builder

RUN apk add --no-cache python3 python3-dev py-pip build-base

# create install directory and switch 
RUN mkdir /install/
WORKDIR /install

# copy the requirement.txt file that should have come from git repo
copy requirements.txt requirements.txt

# go ahead and install the python modules that also came from git
#RUN pip install --install-option="--prefix=/install" -r requirements.txt
RUN pip install -r requirements.txt
