name: Docker Build

on:
  push:
    branches: [ main ]


env:
  AWS_REGION: us-east-2
  ECR_BASE_REPOSITORY: sample-python_base
  ECR_MAIN_REPOSITORY: sample-python_main
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}       
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1          
        
      - name: Get Git Diff
        run: |
          git diff --name-only HEAD~1 HEAD
          echo "Git Diff complete"

      - name: Determine Changed Files
        id: determine-changes
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "::set-output name=files::$CHANGED_FILES"

      - name: Build Base Image
        if: ${{ github.event_name == 'push' && contains(steps.determine-changes.outputs.files, 'Dockerfile-Base') || contains(steps.determine-changes.outputs.files, 'requirements.txt') }}
        run: | 
          docker build -t $ECR_BASE_REPOSITORY:$IMAGE_TAG -f ./Dockerfile-Base .
          # Set the AWS account ID and ECR repository URI
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_BASE_REPOSITORY
          # Tag the Docker image with the ECR repository URI
          docker tag $ECR_BASE_REPOSITORY:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:$IMAGE_TAG          

      - name: Build Main Image
        if: ${{ github.event_name == 'push' && !contains(steps.determine-changes.outputs.files, 'Dockerfile-Base') || !contains(steps.determine-changes.outputs.files, 'requirements.txt') }}
        run: | 
          docker build -t $ECR_MAIN_REPOSITORY:$IMAGE_TAG -f ./Dockerfile-Main .
          # Set the AWS account ID and ECR repository URI
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_MAIN_REPOSITORY
          # Tag the Docker image with the ECR repository URI
          docker tag $ECR_MAIN_REPOSITORY:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:$IMAGE_TAG   

