name: Docker Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Debug Info of event name
        run: echo ${{ github.event_name }}

      - name: Debug Info of Event
        run: |
          echo "Event: ${{ toJson(github.event) }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          echo "Modified Files: ${{ github.event.head_commit.modified }}"
        
      - name: Build Base Image
        if: ${{ github.event_name == 'push' && (contains(github.event.head_commit.modified, 'Dockerfile-Base') || contains(github.event.head_commit.modified, 'requirements.txt')) }}
        run: ls

      - name: Build Main Image
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'Dockerfile-Main') }}
        run: docker build -t main:latest -f ./Dockerfile-Main .

