name: Docker Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
        
      - name: Get Git Diff
        run: |
          git diff --name-only HEAD~1 HEAD
          echo "Git Diff complete"

      - name: Determine Changed Files
        id: determine-changes
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "::set-output name=files::$CHANGED_FILES"

      - name: Build Base Image
        if: ${{ github.event_name == 'push' && contains(steps.determine-changes.outputs.files, 'Dockerfile-Base') || contains(steps.determine-changes.outputs.files, 'requirements.txt') }}
        run: docker build -t base:latest -f ./Dockerfile-Base .

      - name: Build Main Image
        if: ${{ github.event_name == 'push' && !contains(steps.determine-changes.outputs.files, 'Dockerfile-Main') }}
        run: docker build -t main:latest -f ./Dockerfile-Main .

